# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        cache: ~

        # the name of the "filter set"
        thumb_edit_album:
            format: webp
            # adjust the image quality to 75%
            quality: 50

            # list of transformations to apply (the "filters")
            filters:

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                thumbnail: { size: [200, 200], mode: outbound }

        banner_webp:
            format: webp
            quality: 80

            filters:
                thumbnail: { size: [1920, 650], mode: outbound }

        banner_jpeg:
            format: jpeg
            quality: 80

            filters:
                thumbnail: { size: [1920, 650], mode: outbound }

        banner_style2_webp:
            format: webp
            quality: 80

            filters:
                thumbnail: { size: [1920, 400], mode: outbound }

        banner_style2_jpeg:
            format: jpeg
            quality: 80

            filters:
                thumbnail: { size: [1920, 400], mode: outbound }

        card_album_webp:
            format: webp
            quality: 80

            filters:
                thumbnail: { size: [250, 250], mode: outbound }

        card_album_jpeg:
            format: jpeg
            quality: 80

            filters:
                thumbnail: { size: [250, 250], mode: outbound }