vich_uploader:
    db_driver: orm

    mappings:
       photos:
            uri_prefix: /images/upload/photos
            upload_destination: '%kernel.project_dir%/public/images/upload/photos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
